id: A061D4CF0
title: Brief Offering Prayer to Tsiu Marpo
type: translation
pechas:
- I3D889326
- IBDD966A9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:06:21.734635
  last_modified_at: 2023-01-04 13:06:21.734642
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I3D889326/9393: DC9B
  IBDD966A9/CBDD: DC9B
